### ISSUE TITLE
Error during run test with paver

### ISSUE THREAD

**Issue by safo-bora** [jenisys/behave.example#2]
Is it ok to have errors during run example tests?
(Python 3.5, behave 1.2.5)

Can I run test with some python script launcher , without paver magic ? :)

I just run example and see error.

```
C:\Users\USER\Desktop\behave.example-master\behave.example-master>d:\P4\deploy\python35\python.exe bin\pavercmd.py test
---> pavement.test
---> pavement.init
---> pavement.behave_test
bin\behave -f progress --tags=-@xfail features/
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\behave.example-master\behave.example-master\bin\behave_run.py", line 14, in <module>
    from behave_ext.formatter import pretty2
  File "C:\Users\USER\Desktop\behave.example-master\behave.example-master\lib\python2\behave_ext\formatter\pretty2.py", line 6, in <module>
    from behave_ext.terminal import select_terminal_class, get_terminal_size
  File "C:\Users\USER\Desktop\behave.example-master\behave.example-master\lib\python2\behave_ext\terminal\__init__.py", line 45, in <module>
    ColoredTerminalWriter = select_terminal_class(colored=True)
  File "C:\Users\USER\Desktop\behave.example-master\behave.example-master\lib\python2\behave_ext\terminal\__init__.py", line 37, in select_terminal_class
    return winterm.Terminal
AttributeError: 'module' object has no attribute 'Terminal'


Captured Task Output:
---------------------

---> pavement.test
---> pavement.init
---> pavement.behave_test
bin\behave -f progress --tags=-@xfail features/

Build failed running pavement.test: Subprocess return code: 1
```

**Comment by jenisys** [comment]
FIXED: Checkout/pull the git repository again and run the tests.
Note that the project was only prepared for Python 2 support (as ``lib/python2`` and ``setup.py`` indicated).
